- main_test.go
- net/listener_grpc.go
- test/test.go
Fix for #73. I also added a test in main_test.go for ensuring insecure requests for dist_key continue to work.
Test output:
```
$ go test ./...
ok  	github.com/dedis/drand	1.916s
ok  	github.com/dedis/drand/beacon	(cached)
ok  	github.com/dedis/drand/core	(cached)
ok  	github.com/dedis/drand/dkg	(cached)
ok  	github.com/dedis/drand/ecies	(cached)
ok  	github.com/dedis/drand/fs	(cached)
ok  	github.com/dedis/drand/key	(cached)
ok  	github.com/dedis/drand/net	(cached)
?   	github.com/dedis/drand/protobuf/control	[no test files]
?   	github.com/dedis/drand/protobuf/crypto	[no test files]
?   	github.com/dedis/drand/protobuf/crypto/share	[no test files]
?   	github.com/dedis/drand/protobuf/crypto/share/vss	[no test files]
?   	github.com/dedis/drand/protobuf/dkg	[no test files]
? …
```
> Fix #73: Allow insecure requests for drand dist_key

- README.md
- net/listener_grpc.go
Ensures that insecure mode also has an http endpoint for retrieving a distributed key. Also adds brief documentation about how to use the drand beacon's http endpoints.
> Fix issue #79

- main_test.go
- net/listener_grpc.go
Hi there! I figured out the remaining test bug in #73. I was being dumb and invoking 
```
drand control --port <ctrlPort> share
```
instead of the correct invocation,
```
drand control share --port <ctrlPort>
```
Additionally, I cleaned up some additional lines of code for consistency.
Let me know if you want me to split the test fix and the cleanup into two separate PRs!
> Fix remaining test bug in #73 and some cleanup from PR #79

- core/drand_public.go
- ecies/ecies.go
- entropy/entropy.go
- entropy/entropy_test.go
Hi! Thank you for your patience! This is a short and sweet PR that allows participants to feed their own source of randomness into their drand node. The logic defaults to crypto/rand if the custom randomness source fails for any reason.
Some questions I'd like feedback on:
1. Would you prefer that users pass in a `[n]byte` array into `GetRandom` instead of a length, and have the randomness written into that array? This would save us from heap allocations via `make()`.
2. Is this ergonomic enough?
> Add entropy package for incorporating custom sources of randomness

- README.md
As fixed in  https://github.com/dedis/drand/issues/85
> Remove obsolete warning about base-64 encodings

- Dockerfile
- Makefile
- README.md
- main.go
Ready for merge; sample output:
```
drand
NAME:
drand - distributed randomness service
USAGE:
drand [global options] command [command options] [arguments...]
VERSION:
v0.5.0-9-g7f0963f
```
And:
```
drand -v 
drand v0.5.0-9-g7f0963f (date 04/07/2019@10:35:16, commit 7f0963f72779d302a4d8cd51b14276bdb2f17bb0) by nikkolasg
```
The `version` corresponds to the latest git tag.
> Add version number / git commit / date in build and --version text

- README.md
Noticed some typos and odd paragraph behavior in the README.md. This cleans up plenty of typos, wraps all lines at 80 columns, where appropriate, removes unnecessary newlines, addresses English grammar, expands "JS" to JavaScript, and fixes one invalid Markdown syntax.
> Correct typos, fix grammar, wrap at 80 columns, general cleanup.

- core/client_public.go
It looks like `core.Drand` changed to use a [sha256 RandomnessHash](https://github.com/drand/drand/blob/a40dc25e1aec6822a79c72b4aaca12e65c700f01/core/drand_public.go#L99) instead of the sha512 hash it had used earlier. This change did not carry over to [verification in the go client](https://github.com/drand/drand/blob/a40dc25e1aec6822a79c72b4aaca12e65c700f01/core/client_public.go#L115), so it fails to validate correct randomness on retrieval.
Use the sha256 algorithm defined by `RandomnessHash` for the client as well.
> BUG: Use same hash algorithm to generate and verify randomness

- Dockerfile
This extends the current `Dockerfile` in the repository to perform the compilation of the binary in a standardized environment, rather than doing so implicitly.
It also shrinks the execution / final image to a scratch image with only the binary and no additional file system. This reduces the final redistribution size to 19MB from several hundred.
> Multi-stage docker file for building a standalone binary

- Dockerfile
- docker/entrypoint.sh
* Install certificate authorities
* Run on a sandboxed user
* Move to busybox
* Wrap with tiny
* Faster builds
* Automatically generate key-pair when no config present
These changes are ported from go-ipfs and ipfs-cluster which work
reasonably well in Dockerized environments.
> Level up the Dockerfile

- README.md
I will open another PR to restructure the README and add the standard README badge then.
> docs: add go report, reference and version badges

- main_test.go
fix #277 
this was the only place in the tests i saw that was calling `go install` and then expecting the binary to end up on the global path. changed to `build` and looking for it in the local directory.
> use `go build` and test locally to ensure local binary

- client/client.go
- client/client_test.go
- client/http.go
- client/mock_test.go
- client/prioritizing.go
- client/prioritizing_test.go
- client/util.go
A second pass on fleshing out the client library.
The functional options allow us to relatively easily provide a `WithNotifier` hook to allow overlaying the client in #279
> Add prioritizer for multiple URLs, functional option constructor

- README.md
- docker/README.md
Renames README_DOCKER.md to README.md so that it renders on the GitHub dir listing. Updates old references.
@nikkolasg there is an entrypoint script in the folder that is neither listed in the readme's tree nor mentioned anywhere else.
> docs: rename and fix docker readme

- cmd/relay/main.go
- daemon.go
- http/server.go
- metrics/metrics.go
- metrics/pprof/pprof.go
* makes use of pprof a bit safer - only included by binary packages.
* adds HTTP metrics / instruments http server on both drand node and relay
* adds flag to `cmd/relay` for also exposing metrics
> HTTP metrics, exposed on http relay

- cmd/relay/main.go
> log to stdout if not otherwise specified

- client/failover.go
- client/failover_test.go
`NewFailoverWatcher` creates a client whose Watch function will failover to `Get`-ing new randomness if it does not receive it after the passed grace period.
Note: with the failover watcher - if network conditions slow down the delivery of a round, the client will skip as many rounds as the duration of the network condition. i.e. the failover is currently only catering for the case where a pubsub message is not received, not when network issues occur.
TODO:
> feat: add failover client

- client/http.go
If Response.Body is not closed, the connection cannot be reused.
This patch reduces time needed for lotus chain generation and sync tests with
drand from 45s to 18s.
> Close HTTP Response Body after use to allow HTTP Keep-Alive

- client/client.go
This option if set will enable the failover client and configure the time after which a watcher will failover to using client.Get to get the latest randomness.
I will add a test for this when passing a [watcher interface](https://github.com/drand/drand/pull/357) is merged.
> feat: add failover grace period option

- client/http_test.go
- cmd/drand-cli/cli.go
- cmd/relay/main.go
- core/config.go
- core/drand.go
- http/server.go
- http/server_test.go
Defer to @hsanjuan on value of this.
We have metrics that should capture this in influx, but it's nice to be able to go to `/version` and see when the thing you're interacting with was built e.g. to know if a fix should be in the version you're interacting with.
> http export of binary version

- cmd/relay-gossip/lp2p/ctor.go
This allows drand gossip relays to be more easily identified by metrics collectors.
> feat: set libp2p user agent string

- .circleci/config.yml
Currently not included because it is a separate module.
I added a test in https://github.com/drand/drand/pull/404 but it was not showing in codecov.
> fix: run relay-gossip tests on CI 

- client/client.go
- client/client_test.go
- client/failover.go
- client/failover_test.go
When `chainInfo` is not passed to a new client, it's retrieved from `/info` and set on `cfg.chainInfo`.
The `NewFailoverWatcher` constructor was being called outside of `makeClient` so although `makeClient` retrieved `chainInfo` and set it on `cfg.chainInfo`, it was not observed by `NewFailoverWatcher` because `makeClient` is passed a _copy_ of `clientConfig` not a pointer.
This PR moves the `NewFailoverWatcher` constructor into `makeClient`, as well as `NewCachingClient` and `newWatchAggregator`.
> fix: nil pointer when using failover without passing chainInfo

- cmd/relay-gossip/client/client.go
- cmd/relay-gossip/client/relayclient_test.go
- cmd/relay-gossip/main.go
- cmd/relay-gossip/node/relaynode.go
This PR renames network-name to chain-hash and makes the parameter required - this stops the relay or client publishing to a topic with an empty string.
BREAKING CHANGE: the `network-name` option to the relay-gossip CLI has been renamed `chain-hash` and is now a required parameter.
> refactor: rename network-name to chain-hash

- client/client.go
- client/http.go
- client/http_test.go
- client/metric.go
- metrics/metrics.go
Note: merging onto metric branch from @petar 
This adds instrumentation to client HTTP requests to track number in flight, and latency of the different stages of the request.
> instrumentation of http requests

- client/cache.go
- client/cache_test.go
- client/client_test.go
- client/http.go
- client/http_test.go
- test/mock/grpcserver.go
A `Get` with round = 0 implies we want the latest round, not the genesis round. This PR changes the HTTP client to request from `/public/latest` when round 0 is requested and `/public/{n}` otherwise. It also updates the caching client cache key so that a result is stored against it's round number as specified in the result, not against the round number requested (which could be 0!).
> fix: cache for latest value

- client/aggregator.go
- client/client.go
- client/client_test.go
- client/failover_test.go
- client/utils_test.go
- client/watcher_test.go
Adds tests and fixes for the watcher client and watch aggregator client.
1. The watcher client is now created after we have obtained `chainInfo` and it is now passed to the constructor. We never saw the issue because we currently ignore it with the gossipsub client.
1. The aggregator was not closing subscription channels when the source channel was closed.
> fix: watcher and aggregator

- client/client_test.go
- client/http.go
- client/http_test.go
- client/test/mock/httpserver.go
- cmd/relay-gossip/client/client.go
- cmd/relay-gossip/client/relayclient_test.go
- cmd/relay-gossip/main.go
- cmd/relay-gossip/node/relaynode.go
- go.sum
- test/mock/grpcserver.go
- test/mock/httpserver.go
This PR adds a `-http-connect` option that allows the gossip relay to connect with and be a relay for one or more drand HTTP API servers.
The original `-connect` option is renamed as `-grpc-connect` (but still has an alias for backward compatibility).
There is definitely a race bug somewhere in the blocking HTTP server as I'm occasionally getting the error: `ts="Tue, 26 May 2020 00:35:25 BST" call=cache.go:44 level=error polling_client="failed to watch" err=EOF`.
> feat: gossip relay from HTTP CDN

- Makefile
This fixes the `make build` target. It renames `build-relay-http` to
`relay-http` and it adds aliases like `drand-relay-http` (which is actually
the name of the binary being produced).
> Fix Makefile, rename build rules and add aliases

- client/cache.go
- client/cache_test.go
- client/client.go
- client/failover.go
- client/failover_test.go
- client/http.go
- client/interface.go
- client/prioritizing.go
- client/prioritizing_test.go
- cmd/relay-gossip/client/client.go
note: this sets the log output directly emitted by the relay-gossip client,
but doesn't propagate through to the previously constructed `pubsub` object. I think that's probably an okay boundary
> common log interface so that gossip logger can be set

- cmd/relay/main.go
- http/server.go
* set no-cache header on /health
* /health triggers establishment of the background thread if the relay isn't fully started yet
* the relay binary auto-triggers full startup.
> happier health endpoint

- cmd/relay-gossip/main.go
Cleans up the usage documentation for the relay-gossip CLI command.
I've made the `--chain-hash` parameter NOT global, since it's only used by 2 of the 3 commands. It's also currently a _required_ parameter (will be fixed soon) which has the unfortunate consequence with this CLI library of not giving you access to `--help` for subcommands until it's set...and it also stops you from using the `peerid` subcommand even though it's not used here either.
Unfortunately it means this is a breaking change, since the position of the `--chain-hash` param needs to change to be _after_ the `run` or `client` subcommand instead of before.
---
`drand-relay-gossip --help` before:
```console
NAME:
drand-relay-gossip - pubsub relay for randomness beacon
USAGE:
drand-relay-gossip [global options] command …
```
> docs: gossip relay command usage message tweaks

- chain/beacon.go
- chain/beacon/chain.go
- chain/beacon/constants.go
- chain/beacon/convert.go
- chain/beacon/node.go
- chain/beacon/node_test.go
- chain/beacon/sync.go
- chain/beacon/ticker.go
- chain/beacon_test.go
- chain/boltdb/store.go
- chain/boltdb/store_test.go
- chain/convert.go
- chain/info.go
- chain/info_test.go
- chain/store.go
- chain/time.go
- chain/time_test.go
- cmd/drand-cli/cli.go
- cmd/drand-cli/cli_test.go
- core/drand.go
- core/drand_public.go
- go.mod
- go.sum
This breaks down the `chain/` package into
- `chain/` : contains static definitions and helpers (beacon, chain info, store..)
- `chain/beacon/` contains the protocol's logic of the random beacon
- `chain/boltdb` contains the implementation of the store using boltdb
Unfortunately, the goal of removing dependency on grpc is not trivially done. The problem is that `protobuf/` compiled files depends on gRPC. We would need to make maybe an intermediate drand  representation, and/or make a package "convert" explicitely. Note that I'm not sure this goal is worth the complexity: from what I see now, only the client side of the HTTP relay will benefit from that but all the rest HTTP server, gossipsub will still have to import protobuf (and hence gRPC), so ... I'm not 100% sold on the benefit given …
> Refactoring of the chain/ package

- cmd/relay-gossip/client/relayclient_test.go
- http/server_test.go
This PR tries to put explicit timeouts on some tests so that circleCI outputs which tests faileds / took longer than expected
> Fixing deadline time on CI 

- chain/beacon/chain.go
- chain/beacon/constants.go
Reverts drand/drand#533
Appears to cause partials to be dropped and chain to fail to continue after the cache fills up (e.g. after 100 rounds)
> Revert "Fix chain cache DOS vuln"

- core/drand.go
🤦‍♂️ I was getting:
```sh
$ drand util selfsign
No help topic for 'selfsign'
```
> fix: self-sign util command name in error message

- client/optimizing.go
This was previously appearing in the logs as:
```
ts="Wed, 17 Jun 2020 12:06:14 BST" call=optimizing.go:143 level=error optimizing_client=endpoint_temporarily_down_due_to
```
> fix: argument pairs so error message is logged

- client/client.go
- client/mock_test.go
- client/optimizing.go
- client/optimizing_test.go
This PR updates the optimizing client so that when a call to `Watch` on one of the clients fails, it is retried after a while.
It means that if we have gRPC and HTTP clients watching and the gRPC client fails, it can recover, instead of using the HTTP client for ever more.
Kinda more of a fix than a feature now I think about it...
> feat: optimizing client retry watch

- client/aggregator.go
- client/aggregator_test.go
- client/cache.go
- client/cache_test.go
- client/empty.go
- client/empty_test.go
- client/grpc/client.go
- client/grpc/client_test.go
- client/http/http.go
- client/http/http_test.go
- client/interface.go
- client/metric.go
- client/metric_test.go
- client/mock_test.go
- client/optimizing.go
- client/optimizing_test.go
- client/watcher.go
- client/watcher_test.go
- core/drand_proxy.go
- go.mod
- go.sum
- lp2p/relaynode_test.go
This PR adds ~~an optional~~ a `Close` method for clients that have things to close, or have underlying clients that might have things to close :)
The _main_ idea is to be able to terminate any running background processes that the client (or it's underlying clients) creates that would not otherwise be able to be killed externally.
To discuss:
* ~~Should we just add `Close` to the interface? It would remove a bunch of conditionals!~~
* Yes! Done.
* ~~With gRPC, closing the connection will actually also terminate any in-flight `Get`, `Watch` or `Info` requests. With HTTP it's not that easy, we'd have to add some more complicated code to track connections. So for that reason I've kinda left the semantics for `Close` to be that `Get`, `Watch` or `Info` requests _may_ be terminated, at the …
> feat: add Close method to client

- core/drand_control.go
- core/drand_test.go
- core/group_setup.go
> stabilize reshare-preempt test by not deleting preempting manager

- Makefile
- cmd/relay-s3/README.md
- cmd/relay-s3/main.go
- go.mod
- go.sum
This PR adds a CLI program that relays drand randomness to an AWS S3 bucket.
Check out the demo here:
https://youtu.be/YSxOpakChnk
Future PRs:
* Update `/public/latest` when new round is uploaded
* Add `/info` information at startup if not exists
Nice to have:
resolves #351
> feat: relay s3

- README.md
So that the specification and deployment documentation are correctly linked.
> Correcting the drand.love URLs

- demo/regression/main.go
currently the final "swap out one member" check seems to not be passing pretty regularly. lets see if waiting an extra period makes it more stable.
> attempt to stabilize regression ci check

- .github/workflows/lint.yml
- .github/workflows/regression.yml
it appears to time out fetching dependencies / not properly caching them internal to the golangci-lint action task. re-add the explicit `go get ./...` as a precursor step.
> lint CI check still fails

- .github/workflows/release.yml
see: https://github.com/drand/drand/actions/runs/155887827
> Go-Releaser expects to run `go generate`, which now needs `protoc`

- README.md
- cmd/drand-cli/cli.go
drand received an audit and is now considered suitable for use in production environments
> fix: remove audit/production warning banner

- client/optimizing.go
I believe this was added while debugging locally and never removed.
When asking for **round 0** the following is erroneously printed:
```
got unexpected round back in OC get call HTTP("https://pl-us.testnet.drand.sh").(+verifier)
```
> fix: remove println

- client/optimizing.go
when the optimizing client attempts to cycle underlying watched clients, it will close them, and when they subsequently report done, it will not need to do additional cleanup.
> client closing was warning in normal operation

- core/drand_test.go
Since both the out and err channels can close at the same time there's a possibility go will select a closed out channel when there's an error.
> fix: follow chain nil pointer

- client/verify_test.go
Just adds a test to increase coverage that runs the code path that has to get intermediate rounds between point of trust and requested round.
> test: old verified result

- client/aggregator.go
- client/aggregator_test.go
- client/cache_test.go
- client/client.go
- client/client_test.go
- client/test/result/mock/result.go
The optimizing client will retry failed clients but if _all_ of them fail and are put in backoff then the watch channel will be closed. If this happens then the auto watch will stop forever and there's no way to restart without creating a new client.
This PR changes the auto watch functionality so that if the auto watch channel gets closed, then it is re-opened after 30s. It adds `WithAutoWatchRetry(time.Duration)` option to allow people to customise or disable it.
Maybe this should be a separate client? It's not really tied to the aggregator anymore.
> fix: retry auto watch

- core/drand_control.go
> cleanup 'drand.dkgInfo' field after reshare attempt completes or fails.

- client/doc.go
- client/grpc/doc.go
- client/http/doc.go
- lp2p/client/doc.go
Client documentation and examples should live as part of the Go documentation
as it is normal and expected in Go programs.
Leaving essential information about client code usage away from the Go
reference documentation (where Go developers will look for docs) is no good.
Also, docs should be maintained with code by the developers.
The drand.love website should send people here.
> Import client docs

- http/server.go
Possible source of bugs in the future but not currently a problem, as `h.chainInfo` is never set *to* `nil` but *from* `nil`.
`getChainInfo` could sometimes unnecessarily return `nil` if `h.chainInfo` were set to `nil` after releasing the `h.chainInfoLk` read lock.
Also remove direct, unsynchronized access to `h.chainInfo` in `h.getRand()`. Similarly not a bug in the current usage, but could be a source of crashes if `h.chainInfo` is set to `nil`, or `h.getRand()` isn't called after a previous call to `h.getChainInfo()`
> Fix suboptimal lock release in `(*handler).getChainInfo`.

- README.md
It uses sha256 not sha512:
https://github.com/drand/drand/blob/39ef471174306fa25859f571abbc245c5fd4a590/chain/beacon.go#L54-L57
> docs: correct hashing algo used for randomness

- fs/fs.go
Just some small changes to the comments and use of constants in `fs`.
> Typos and constants

- cmd/drand-cli/cli.go
- cmd/drand-cli/control.go
- demo/node/node_subprocess.go
Secret can still be specified via the `DRAND_SHARE_SECERT` env var
> switch from `--secret=<hex>` to `--secret-file=<filename>`

- README.md
Link currently do not properly forward and lose their path and might as well point to the actual site now.
> docs: remove drand beta links

- client/empty.go
- client/optimizing.go
* when the libp2p client is marked 'passive' we should also not end up in cases where it is the first client to be queried when `Get` is called.
* Changes error bubbling in the optimizing client to not only return the final sub-client error.
> Deprioritize passive clients in optimizingclient.get

- core/drand_metrics.go
Rationaly here is that any metric scraper should support be configured in the
same way regardless of the peer. By skipping a handler for the current peer we
are creating an "exception" unique to every peer, which only makes things more
difficult to maintain on infra-side of things.
Also, chances are the index mapping is somehow borked, since in my tests it is
sometimes skipping the current node and sometimes a different node, so this might
fix that altogether.
> Expose own metrics in /metrics/peer/

- http/server.go
It was possible for a sequence to occur of:
* Watch loop pulls pending list. unlocks lock.
* Waiter triggered by 'Done' context gets lock. checks list and sees it isn't there. closes it's watch channel.
* Watch loop attempts signalling waiter on now-closed channel. panics.
This keeps the lock held by the watch loop during signalling.
> more conservative channel behavior for waiters

- client/aggregator.go
- client/aggregator_test.go
- client/cache_test.go
- client/client.go
- core/drand_public.go
- lp2p/client/client.go
when a watch client is provided, but autowatch is not enabled,
we should still track the passive client's watch channel at an aggregator level for caching purposes.
> pasive watch mode

- .github/workflows/release.yml
previous run failed because this was using an insecure feature of github actions they've recently disabled.
> bump protoc version in goreleaser

- client/client_test.go
- client/interface.go
- client/random.go
- client/test/result/mock/result.go
- client/verify.go
- client/verify_test.go
- test/mock/grpcserver.go
Attempt at limiting the Result interface to a smarter `Signature`. Test compatibility not dealt with here.
> remove SignatureV2 interface method

- core/broadcast.go
- core/broadcast_test.go
- core/drand.go
- core/drand_control.go
Tests were always passing locally on my machine but apparently not on Travis - I switched to having tests based on callbacks so travis weird timings doesn't influence test outcome.
> Test for broadcast based on callbacks instead of timeouts

- .github/workflows/release.yml
unclear why this behavior changed on newer go 1.14.
unclear if there's anything else that could cause it from google searches
> fix unclean go.mod in go-releaser automation

- test/mock/grpcserver.go
There was a 'probably safe' issue with reading from a channel variable directly, vs a reference within it. This seems to fix the race detector.
> fix race in http test

- core/migration/migration.go
- fs/fs.go
It solves issues reported on https://github.com/drand/drand/issues/855
> Fixes applied to migration process

- .github/workflows/release.yml
We bumped versions used in ci/tests, but not the ones goreleaser attempts to use when compiling at the end, so it's build will fail.
> harmonize go releaser config versions

- cmd/drand-cli/control.go
- common/beacon.go
- common/beacon_test.go
- core/drand_beacon_control.go
- core/drand_daemon_helper.go
- test/docker/utils/reshareBeacon.sh
**Context**
This bug allows a user to init a reshape process with a difference between the beacon id he sets on CLI command and the ones present inside config file.
**Explanation**
Two networks are working inside the nodes: the default and a second one. We start a reshare on the second one to add a new node to this network. This new node uses the flag `--from` on CLI reshare cmd, but the user forgets to set the `--id` flag. The new node which is being added to the network uses the default one as the "resharing beacon process" instead of the second one. When it tries to send its share to the leader node, it uses the beacon id present on the old config file (it is the correct one). For that reason the leader is able to start the dkg process... as a result, the new node is not on the new …
> Fix bug on reshare process

- cmd/client/main.go
- cmd/drand-cli/cli.go
- cmd/drand-cli/control.go
- cmd/drand-cli/daemon.go
- cmd/relay/main.go
- http/server.go
- log/log.go
- test/docker/Dockerfile
- Fix chain hash format on error description
- Remove panic from drand-client cmds
- Fix default logger func
- Change http status code on group file not found over http server
- Improve logic on relay code to handle `--hash-list` flag better
- Add gossip binary to dev image
- Deprecate `--hash` flag on relay http.
> Various fixes

- chain/verify.go
- client/verify.go
On unchained randomness previous signature won't be present, so the verifying client should handle that scenario correctly.
> Fix important issue on verifying client

- chain/beacon/node.go
- core/broadcast.go
- core/drand_beacon_control.go
- go.mod
- go.sum
- log/log_test.go
This fixes #914 and fixes #812, I've added a test too, but ideally we should test all test outputs for "missing keys" in logs too.
The problem was mostly that we had logs that were not in proper `"key", "value"` format and weren't showing properly. 
I am going to back-port this to v1.13.1 as well.
> Some log fixes

- .github/workflows/tests.yaml
When devloping on a branch in the drand repo, we are running the CI on all pushes currently.
This changes the Github Action so that we are only running CI on PR and when pushing something on master or on a release branch.
> [CI] Avoid running tests on both the branch and the PR

- .golangci.yml
- chain/beacon/chain.go
- chain/beacon/node_test.go
- chain/beacon/store.go
- client/client_test.go
- client/http/http.go
- client/http/http_test.go
- client/optimizing.go
- cmd/drand-cli/cli.go
- core/drand_beacon_control.go
- core/drand_test.go
- core/util_test.go
- lp2p/client/client.go
- net/client_grpc.go
- net/control.go
We had deferred calls that were issued in a for loop, and as such were "leaking".
This PR wraps the deferred calls and code into anonymous function, which means that the deferred calls are run at the end of each iteration instead of leaking until the end of the function execution.
> [Cleanup] Avoid leaking deferred calls

- chain/beacon/node.go
- core/broadcast.go
- core/drand_control.go
- go.mod
- go.sum
Backport from master, see #920
> Fixing logs

- .github/labels.yml
- chain/beacon/chain.go
- chain/beacon/node.go
- chain/beacon/node_test.go
- chain/beacon/store.go
- chain/beacon/sync.go
- core/broadcast.go
- core/drand_beacon.go
- core/drand_beacon_control.go
- core/drand_beacon_public.go
- core/drand_daemon.go
- core/drand_daemon_control.go
- core/group_setup.go
- demo/node/node_inprocess.go
- log/log.go
- Using With for prefixes
- Logs cleanups
- Trying to add more useful information in logs, including node address and index
Before:
```
2022-03-07T18:13:08.781+0100	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:37900", "round": 1, "len_partials": "2/2"}
2022-03-07T18:13:08.781+0100	DEBUG	beacon/node.go:106		{"beacon_id": "", "received": "request", "from": "127.0.0.1:38166", "round": 1}
2022-03-07T18:13:08.784+0100	DEBUG	beacon/node.go:136		{"beacon_id": "", "process_partial": "127.0.0.1:38166", "prev_sig": "bffcfc", "curr_round": 1, "msg_sign": "e38cc7", "from_node": "127.0.0.1:34863", "status": "OK"}
2022-03-07T18:13:08.785+0100	DEBUG	beacon/node.go:136		{"beacon_id": "", "process_partial": "127.0.0.1:40218", "prev_sig": "bffcfc", "curr_round": 1, "msg_sign": …
```
> Logging improvements

- demo/demo_test.go
It seems the CI is slower these days and this makes our tests fail without the demo being actually stuck.
> Letting more time for the demo to timeout

- demo/lib/orchestrator.go
We used to panic if the signature didn't match before making sure we had fetched the proper rand.
This should fix #807 definitively.
> Properly retrying to fetch current beacon in the demo

- core/drand_daemon.go
- metrics/metrics.go
I noticed that when the node starts up no status is emitted until the moment that a DKG or Reshare starts. This fixes it, and adds a status for when the node shuts down.
Part of https://github.com/drand/drand/issues/941
> Emit DKG/Reshare status when node starts up/shuts down

- .github/workflows/lint.yml
- .github/workflows/regression.yml
- .github/workflows/tests.yaml
This will avoid having us wasting CI minutes on runs that should stop because a new push was done on the same branch.
> Avoiding concurrent CI actions

- .github/workflows/publish_tagged.yaml
- Cleaning up the regex for tags to support pre-releases such as the `v1.4.0+testnet` we just released.
- Adding a manual trigger to the deploy tagged image workflow and making it auto-published tags too.
- Removing the major / minor args we were passing as Env var to the Makefile previously since these are now hardcoded as per #956
> Patching deploy docker GHA

- .github/workflows/publish_tagged.yaml
- common/version.go
- common/version_test.go
Since docker images cannot be tagged using a tag name containing a "+", we can use it for our versions as well.
> Using - instead of + for pre-releases for docker compat

- chain/info.go
- core/drand_beacon_control.go
- core/drand_daemon_helper.go
- key/group.go
The changes in #979 are too numerous and aren't playing nicely with some of our file handling, and regression tests, it will need more attention in the future. 
This should fix our issues for now.
> Minimum changes for fixing 1.4.0 follow capabilities.

- core/drand_daemon_helper.go
if the daemon got a grpc request specifying a chain hash, but didn't recognize it, it would go on with the default beacon. it should fail those requests.
> fail beaconID reads for unknown chain hashes

- cmd/relay/main.go
- core/drand_daemon_helper.go
* print out hex of passed in hash
* use the same cli.Context to make sure args are passed through
> revert relay to using a single command to make sure grpc endpoint is parsed correctly.

- core/drand_beacon_control.go
The backup utility attempts to open the backup file with WR permissions,
but if the file does not yet exist it is created with 000 permissions.
This means that subsequent attempts to write backups to the same file
will fail.
> Create backup file with RW permissions

- core/drand_beacon.go
I've checked and the DKG state metric is emitted in both places that `WaitDKG` is called, so this one is extraneous (and wrong).
> Always emit DKGDone metric when DKG is finished

- cmd/drand-cli/cli_test.go
- core/drand_daemon.go
- core/drand_daemon_test.go
- net/control.go
- net/control_test.go
- attempting to set a control port that has already been bound no
longer panics
resolves #1019
> No panic on creation of drand daemon on bound port

- metrics/metrics.go
From my reading this should not be necessary, but it was the cause for the panics on testnet when trying to update to commit `f9a81d`. See logs at https://my.papertrailapp.com/groups/20050302/events?focus=1481660778657517579&q=drand.testnet2.drand+
> Verify that a peer's metrics handler is non-nil

- chain/beacon/node.go
- chain/beacon/node_test.go
- chain/beacon/sync_manager.go
- core/drand_test.go
- core/util_test.go
If a node joins the DKG but goes unresponsive before completion, its
index can be missing from the group file.  If it comes back online
and starts sharing partial signatures, it can cause a segfault on the
nodes still in the network
> Fixed segfault if nodeId out of range

- cmd/drand-cli/cli.go
- cmd/drand-cli/public.go
- core/drand_beacon_control.go
- fs/fs.go
Prior versions of the cli tool allowed comma separated strings for
aliases, but they no longer work. Updated to the array alias format
despaghettified some things on my adventure
> Force flag -f alias migrated to new format

- cmd/drand-cli/cli.go
- cmd/drand-cli/cli_test.go
- cmd/drand-cli/control.go
- core/drand_beacon_control.go
Improved error messaging when using invalid flags for resharing
renamed transition flag to reshare, retaining transition as an alias
> Improved error messaging when using invalid flags for resharing

- README.md
- core/drand_beacon_control.go
- core/drand_beacon_public.go
- core/drand_daemon_control.go
- core/drand_test.go
- net/client.go
Passing an invalid beaconId or missing out the flag on a new node
without a default beacon would segfault taking down the host node.
Also, not passing an old group info to a reshare would also segfault the
host node.
Added some checks and tests for both.
> Fixed reshare segfaults on invalid beaconId

- cmd/drand-cli/cli.go
putting the --id flag after the cmd args ignores it (see: https://github.com/urfave/cli/issues/585), but it isn't clear
where the command actually looked for the keypair
> Show full path of duplicate keypair

- chain/beacon/node_test.go
- chain/beacon/sync_manager.go
Old nodes don't have a metadata object, as they did not support
multibeacon
Assume these nodes wish to sync default.
> Allow old nodes to sync

- cmd/drand-cli/cli.go
- cmd/drand-cli/cli_test.go
- go.mod
Fixed a bug where empty input to select the default port during keygen
would repeatedly prompt for input rather than select the default port
(8080)
Updated to the latest urfave CLI in order to enable manipulation of the
CLI `Reader` for testing
Modified some sections of the CLI to use the `Reader` from the `App`
rather than assuming it is always stdin
Modified some of the prompts to end in a full stop for consistency
> fixed default port selection in keygen

- core/broadcast.go
- core/constants.go
- core/drand_beacon.go
- core/drand_beacon_control.go
- core/drand_beacon_public.go
This is adding a few more logs to our DKG.
Notice that the phaser will always proceed with its phases in order, just waiting its timeout time between each phases, without checking whether or not the phase was "successful" or not. 
This might be something we might want to rework in the future...
> Adding logs of disqualified nodes during DKG

- .github/workflows/tests.yaml
- core/util_test.go
This is enabling Debug level logs in our tests, in order to help us debug our CI issues and flaky tests. (Most notably the stalled `make coverage` issues we seem to only have on the CI)
It is also adding some extra history to our race traces and stripping the specific GH prefixes from them, to allow for an easier usage when importing the logs locally.
> Enabling Debug level logs in tests

- chain/beacon/callbacks_test.go
- chain/beacon/node_test.go
- chain/beacon/store_test.go
- chain/boltdb/store_test.go
- cmd/client/lib/cli_test.go
- cmd/drand-cli/cli_test.go
- core/util_test.go
- lp2p/client/client_test.go
- lp2p/ctor_test.go
- lp2p/relaynode_test.go
- net/control_test.go
A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
require.NoError(t, err)
defer os.RemoveAll(tmp)
// now
tmpDir := t.TempDir()
}
```
> test: use `T.TempDir` to create temporary test directory

- .golangci.yml
All unused linters are now turned off as described by golangci-lint.
Deprecated linters are also turned off by default.
Some noisy linters are turned off too with mentions of which could be later turned on again.
> Update .golangci.yml file per linter recommendation

- .golangci.yml
- chain/beacon/node_test.go
- chain/beacon/sync_manager.go
- cmd/drand-cli/cli_test.go
- common/version.go
- core/broadcast.go
- core/broadcast_test.go
- core/drand_beacon.go
- core/drand_beacon_public.go
- core/drand_beacon_test.go
- core/drand_daemon_control.go
- core/drand_test.go
- core/util_test.go
- demo/lib/orchestrator.go
- fs/fs_test.go
- key/group_test.go
- key/store_test.go
- lp2p/addrutil.go
- lp2p/client/client.go
- lp2p/client/client_test.go
- lp2p/relaynode.go
- net/gateway_test.go
- test/mock/grpcserver.go
This is doing a couple of different things:
- Bump the version to 1.4.7
- Address some linter complaints
- Make sure we are consistently deleting temporary files
- Make sure nodes are shutdown after each test
> Bump version and cleanup tempdir usage

- chain/boltdb/store.go
- core/drand_beacon_control.go
Remote status calls print out some info about each node's view of the world, including the current number of beacons in their database. The remote status call requests a beacon DB length check but does not actually use it in the corresponding CLI output.
I've replaced its value with one interpolated from the beacon count for backwards compatibility as it's in the protobuf message, but it could probably be removed
> Removed a slow and unnecessary DB length check in status command

- cmd/client/main.go
- cmd/drand-cli/cli.go
- cmd/relay-gossip/main.go
- cmd/relay-s3/main.go
- cmd/relay/main.go
With this PR:
- Bash completion is possible. See https://cli.urfave.org/v2/examples/bash-completions/#enabling for how to turn it on.
- Environment variables can now be used to specify options to the CLI. For now, all the flags can be specified.
> CLI: Support env vars and turn on Bash completion support

- chain/beacon/callbacks_test.go
- chain/beacon/chain.go
- chain/beacon/node.go
- chain/beacon/node_test.go
- chain/beacon/store.go
- chain/beacon/store_test.go
- chain/beacon/sync_manager.go
- chain/boltdb/store.go
- chain/boltdb/store_test.go
- chain/errors/errors.go
- chain/store.go
- client/client_test.go
- cmd/drand-cli/cli.go
- cmd/drand-cli/cli_test.go
- core/drand_beacon.go
- core/drand_beacon_control.go
- core/drand_beacon_public.go
- core/drand_test.go
- core/util_test.go
- test/log.go
This PR performs the following:
- Updates the bolt implementation to pass the logger directly to the implementation.
- Adds the error to the existing methods of the Store and Cursor interface. 
- Returns the type rather than the interface for the bolt storage implementation.
- Cleans up some places by adding error handling.
- Adds the Context parameter to the existing methods of the Store and Cursor interfaces.
It's a precursor for #913 and improves the system stability/usage.
In the process, some tests were identified as not passing due to not handling errors correctly.
These should be rectified in a separate PR.
They also lead to the coverage dropping a bit, since now some parts of the code are left out.
> Update the Store and Cursor interfaces to accept Context and return errors

- cmd/drand-cli/cli.go
This PR adds the flags in #1088 as hidden flags.
This is required to allow the Regression test to pass the initial run phase, where the supplied flag, `--db` and `--pg-dsn`, are missing on the current version of the master branch.
Because they are hidden, there is no UX impact on those using the latest master and they'll be made visible when #1088 gets merged.
> Add hidden DB configuration flags in preparation for #913

- Makefile
go-acc hides the test running.
This can result in coverage tests failing without a clear indication of where the failure happened.
`go-acc` is also rendered unneeded by the recent versions of Go, which added support for correct coverage across packages/tests.
> Replace go-acc with go test

- cmd/drand-cli/cli_test.go
This PR removes the need for sleep during the DKG setup phase for `TestDrandReloadBeacon` and `TestDrandLoadNotPresentBeacon`.
Since it was possible for the `time.Sleep` to run faster than the DKG process, tests could fail.
With this approach, we now wait for DKG to finish before moving forward with the test.
> Remove the need for sleep while DKG is set up during TestDrandReloadBeacon

- README.md
Updating golang readme shield icon to golang version 1.19
> Update golang readme shield icon to version 1.19

- chain/store.go
- core/drand_beacon_test.go
- core/drand_daemon.go
- core/drand_daemon_test.go
- metrics/metrics.go
With this change, the storage backend is reported to Prometheus.
Depends on #913 to be merged first.
> Metrics: Report storage backend

- .github/CODEOWNERS
- core/drand_beacon_public.go
- core/drand_test.go
This is fixing #1119.
It also fixes another problem that arose in https://github.com/drand/drand/actions/runs/3903064598/jobs/6666924292#step:5:14291 where the TestRunDKGReshareTimeout was actually already past its transition time for the second group because it was running too many `AdvanceMockClock` while the `dt.RunReshare` was also running these.
This also adds a CODEOWNERS file to the repo.
> Fixing 2 tests & add code owners

- .github/workflows/tests.yaml
- chain/beacon/chain.go
- chain/beacon/node.go
- chain/beacon/node_test.go
- client/aggregator.go
- cmd/drand-cli/cli.go
- cmd/drand-cli/cli_test.go
- core/drand_beacon_test.go
- core/drand_daemon.go
- core/drand_daemon_control.go
- core/drand_daemon_test.go
- core/util_test.go
- demo/demo_test.go
- net/control.go
- net/gateway.go
- net/listener.go
This PR refactors the order of shutdown calls to allow the clients to exit, then they get the connection terminated.
When stopping a BeaconProcess, it now waits for the process to stop before exiting completely.
For the Daemon, the connection will try to end gracefully, then, if it fails, we'll forcefully terminate it, replicating the existing behavior. The change is that we try to close the connections first, then terminate the network listener, not the other way around.
Finally, it fixes the GitHub Actions runners.
> Refactor shutdown order

- cmd/drand-cli/cli_test.go
- core/drand_beacon.go
- core/drand_beacon_test.go
- core/drand_daemon_test.go
- core/drand_test.go
- core/util_test.go
This PR makes the switch from using `assert.*` functions to their `require.*` equivalent.
With this change, it's now possible to catch when some tests fail without meaningful output, caused by the `assert` call.
> Switch to use require instead of assert

- .github/workflows/lint.yml
- chain/beacon/node_test.go
- cmd/drand-cli/public.go
- core/drand_beacon.go
- core/drand_beacon_test.go
- core/drand_daemon_helper.go
- core/drand_test.go
- core/util_test.go
- demo/lib/orchestrator.go
- demo/regression/main.go
This PR is a continuation of #1099 and should be merged after it.
After starting the daemon with the memdb storage, all beacons will synchronize from genesis.
With this change, a beacon starting with memdb will first sync the last round and then start, thus shortcutting the need to sync all previous values.
> Start in memory operations from specific beacon

- key/keys.go
An error that must not be handled as an error but as a special migration case from previous versions was being returned. 
This is now patched.
> [Fix] Loading group properly

- core/drand_beacon.go
- core/drand_beacon_control.go
- core/drand_beacon_public.go
- core/drand_daemon_helper.go
In order to avoid blocking necessarily on SyncChain or ChainInfo requests, which slows down Partial aggregation.
> Using a RW mutex on BeaconProcess

- .github/workflows/lint.yml
- .github/workflows/regression.yml
- .github/workflows/tests.yaml
- Makefile
This PR addresses the following issues:
- The regression tests were running `make build .` instead of `make build`
- The regression tests were not using the unchained network, nor the new unchained on g1 network
- The regression tests were not using the GitHub Actions matrix style to compose the regression tests
- Aligns the tests and lint Actions to use the GitHub Actions matrix style of composition
- Passes https://rhysd.github.io/actionlint/ with no errors or warnings
This PR partially addresses #1118
> Improve the regression testing with GitHub Actions

- chain/beacon/chainstore.go
- common/version.go
This is to avoid problems where there is only a check done on the remote version and not on the local version.
Unlikely to happen unless crafted packets, but now it's better
> Another fix to the version

- crypto/schemes.go
Since otherwise the json marshaller tries to marshal functions.
> Avoiding json issues when printing scheme

- chain/beacon/callbacks_test.go
- chain/beacon/chainstore.go
- chain/beacon/node.go
- chain/beacon/node_test.go
- chain/beacon/store.go
- chain/beacon/sync_manager.go
- chain/beacon/sync_manager_test.go
- common/version.go
- core/broadcast.go
- core/config.go
- core/drand_beacon.go
- core/drand_beacon_control.go
- core/drand_beacon_public.go
- core/drand_daemon_control.go
- demo/lib/orchestrator.go
Fixes #1020
- Use a RWMutex for CallbackStore
- Have a single go routine per callback and remove callback workers entirely
- Make sure that a new callback being added with the same id will cancel and remove the old one
- Have a single SyncChain callback per remote node instead of opening a new one for each
> Easying the syncing issues

- chain/boltdb/boltdb_test.go
- chain/boltdb/trimmed.go
This PR allows the BoltDB bucket to be as compact as possible.
When using the new DB format:
- The space usage is cut in 1/2 from ~800MB to ~400MB on an older testnet backup.
- The time required to read all beacons from the db drops from ~26ms to ~16ms.
> Set the bucket fill percentage to 100% since we have an append-only workload

- cmd/drand-cli/cli_test.go
- Use the scheme names in the TestKeyGen test
- And reduce the amount of useless logs in TestDrandListSchemes
> Some small test changes

- Makefile
- chain/beacon/callbacks_test.go
- chain/beacon/chainstore.go
- chain/beacon/node.go
- chain/beacon/node_test.go
- chain/beacon/store.go
- chain/beacon/sync_manager.go
- chain/beacon/sync_manager_test.go
- chain/boltdb/store.go
- chain/boltdb/trimmed.go
- chain/boltdb/trimmed_test.go
- chain/postgresdb/pgdb/pgdb.go
- chain/postgresdb/pgdb/pgdb_test.go
- cmd/drand-cli/cli.go
- core/drand_beacon_control.go
- core/drand_beacon_test.go
- demo/cfg/container.go
- demo/lib/orchestrator.go
- demo/postgresdb_test.go
- go.mod
- go.sum
- http/server.go
- http/server_test.go
- test/test.go
This PR improves the following:
- It changes the order of the chain store execution.
- It returns an error if the append store declined to store the same round as the latest one.
- It fixes the tests reusing the port they requested across tests. **_!This works only in CI._** For local development, run with `CI=true` and then clean the temporarily created file under `path.Join(os.TempDir(), ".drand_test_ports")`. Use the `FreeBind()` helper to guarantee the free port.
- It makes `TestHTTPWaiting` runnable again. The issue was caused by a race between receiving the beacon and making the request for it.
- It clarifies why some tests are skipped.
Misc changes:
- It makes the production logs less noisy by moving the Cursor.Next() error to the Debug level when it's expected to an …
> Change the order of stores in chain store. Improve tests

- cmd/drand-cli/cli_test.go
- crypto/schemes.go
This PR fixes the `crypto.Scheme` struct error when trying to marshal it into a TOML format.
It also marks the `TestStartWithoutGroup` as runnable again.
> Allow crypto.Scheme to be marshaled into TOML. Fix TestStartWithoutGroup

- chain/beacon/node.go
- core/drand_beacon.go
- core/drand_beacon_control.go
- core/drand_beacon_test.go
- core/group_setup.go
- core/util_test.go
- demo/main.go
This PR:
- Improves context cancel checks in a few more places.
- Adjusts the Transition time after a reshare command to avoid the logs with `bls: invalid signature` due to nodes not being present in the new network yet.
- Fixes the demo code not finishing in CI.
> Adjust transition time. Fix demo not finishing in CI

- .github/workflows/tests.yaml
- Makefile
- demo/boltdb_test.go
- demo/demo_test.go
- demo/memdb_test.go
- demo/postgresdb_test.go
This PR changes the way we run integration tests, especially related to the `demo` code.
Now:
- The integration tests are now their own separate jobs instead of steps in the original test jobs.
- There are a couple of separate demo runners to be used for running the `test-demo` and `demo` itself.
> Improve GitHub Actions to shorten the run time of tests

- chain/store.go
- core/drand_daemon.go
- metrics/metrics.go
Tested with:
- for current node:
```
drand_node_db{db_type="memdb"} 3
```
- for other nodes
```
drand_node_db{db_type="memdb"} 3
drand_node_db{db_type="bolt"} 1
```
> Report the db type to the group

- chain/beacon/node.go
- cmd/drand-cli/cli.go
- core/drand_beacon_control.go
- internal/context/context_test.go
In order to reduce the CPU load of drand nodes, let us not process partials for rounds we've already aggregated and stored.
This also reworks a few logs.
And it prevents a common issue with `generate-keypair` that we identified during the last ceremony, which is to add flags after the node address, which aren't recognized as flags but as arguments.
> Misc changes & do not process partials for already stored nodes

- chain/postgresdb/database/database.go
- cmd/drand-cli/cli.go
This PR adds the `max-idle` and `max-open` options to the CLI documentation.
It also adds the `connect_timeout` to the supported configuration options.
> Add missing Postgres options to documentation and configuration toggles

- chain/beacon/node.go
- cmd/drand-cli/cli.go
- core/drand_beacon_control.go
- internal/context/context_test.go
* Do not accept more than 1 arg in generate keypair
* Query all nodes for connectivity during remote-status call
* Adding test to context package
* removing unused error
* nicer logs in node.go
* Do not process partials for already stored beacons
This is merging #1197 and #1203 on master as well (it's already on develop) in order to issue a patch release that should reduce CPU usage of our mainnet nodes.
> Do not process partials for already stored nodes (#1197)

- chain/beacon/node.go
If a received partial is specifying our own node index, either our node or the other node is using a wrong group file.
This can happen typically when a node leaves the network during a resharing but keep running after the resharing with its old groupfile.
> Reject invalid self-index in received partials

- .gitignore
- cmd/client/lib/cli.go
- cmd/relay-gossip/README.md
- cmd/relay-gossip/main.go
- go.mod
- go.sum
- lp2p/client/client.go
- lp2p/relaynode.go
This PR adds support for `--hash-list` as a way to specify multiple hashes.
It also allows for multiple `-group-conf` values to be specified via `,` delimiter between values.
Finally, it keeps all the original functionality/library signatures, so it's a drop-in replacement for the current implementations using this library.
Fixes #1196.
> Support hash list in gossip relay

- cmd/relay-gossip/main.go
`-hash` support is back to gossip relay
> Fix support for hash flag in gossip relay

- core/util_test.go
- test/test.go
Instead of logging, let's make sure the error triggers a proper test failure.
> Handle error in test

- .github/CODEOWNERS
Order is important, `develop` will only have @CluEleSsUK and myself as owners now.
> Avoid notifying everyone for develop PRs

- chain/beacon/node.go
- go.mod
- metrics/threshold_monitor.go
- metrics/threshold_monitor_test.go
beacon processes now log some error and warning messages whenever we get close to or cross a threshold number of failures per node
> threshold monitoring for beacon processes

- cmd/relay/main.go
- crypto/schemes.go
- go.mod
- go.sum
- internal/chain/beacon/chainstore.go
- internal/chain/beacon/sync_manager.go
- internal/core/drand_beacon.go
- internal/core/drand_beacon_control.go
- internal/core/drand_daemon.go
- internal/dkg/broadcast.go
- internal/drand-cli/cli_test.go
- internal/metrics/tracer.go
Addressing my own code review comments from #1199 
Most notable change: trying to use plain context.Context instead of otel SpanContext when possible in function APIs.
Note: care must be taken not to reuse a context that's coming from a stream in e.g. broadcasting since it could get canceled too early
> Addressing comments for #1199

- demo/node/node_subprocess.go
- internal/core/drand_beacon.go
- internal/dkg/state_machine.go
- internal/dkg/state_machine_test.go
- internal/drand-cli/dkg_cli.go
- internal/drand-cli/dkg_cli_test.go
Comments from https://github.com/drand/drand/pull/1218#pullrequestreview-1426748768
> Miscellaneous fixes from merged reviews

- internal/drand-cli/cli.go
To ease the transition.
PR against the v2 feature branch directly.
> Avoid erroring out on --insecure with drand start

- cmd/drand-cli/cli.go
Backporting #1287 to master just in case...
> Make sure to error out in generate key pair if key exists

- client/verify.go
- client/verify_test.go
> validate round number on returned beacons

- crypto/curve_test.go
- demo/node/node_inprocess.go
- internal/core/drand_beacon.go
- internal/core/drand_daemon.go
- internal/dkg/actions.go
- internal/dkg/dkg_process.go
- internal/dkg/dkg_process_test.go
- internal/dkg/execution.go
- internal/util/fan_out_chan.go
- added a fan-out channel to ensure that multiple DKGs can be in flight
- added a test for multiple DKGs happening at the same time
- refactored DKG process tests not to use an interface so we can grab a  reference to the channel
> use fan-out channel for DKG results

- internal/drand-cli/control.go
This is a migration path from old keys to new ones.
> Rely on the group scheme name when self-signing a key

- Makefile
- demo/main.go
- internal/net/client_grpc.go
- internal/net/conn_other.go
- internal/net/conn_tls.go
But we still use TLS in prod.
Note that now you need to use `go test -tags test ./...` when running locally, sadly.
There isn't any official build tags for tests in Go, sadly: https://github.com/golang/go/issues/21360.
> Do not use TLS GRPC in test

- internal/metrics/pprof/pprof.go
- internal/net/conn_other.go
- internal/net/conn_tls.go
Seems you cannot nest ServeMux-es into one another without either triming the prefix from the path or just specifying the whole path.
Also to avoid leaking grpc callbacks, we need to close our outgoing connections when we re-establish them.
> Fixing our pprof routes and closing our GRPC conn.

- common/key/store.go
- internal/dkg/actions.go
- internal/dkg/actions_active.go
- internal/dkg/actions_passive.go
- internal/net/client_grpc.go
- internal/util/participant_utils.go
- internal/util/util_test.go
- test/regression/regression_test.go
This does a few things:
- changing `util.Without` to delete all instances of needle, not just the last one, it also now does so without a single allocation
- we don't need a `done` channel to signal when we are done if we can simply close the `error` channel instead, changing gossip accordingly
- removed constants from `sendToPeer`
- reduced allocations in `Packet`
> Some code cleanups in DKG

- .golangci.yml
- internal/core/convert.go
- internal/core/drand_proxy.go
- test/mock/grpcclient.go
We need to delegate computing it to clients/v1 relays instead of still sending it over the wire.
> Do not send randomness over the wire, compute it

- internal/core/drand_daemon_control.go
- internal/dkg/actions_passive.go
- internal/dkg/actions_signing.go
- internal/dkg/broadcast.go
- internal/dkg/broadcast_test.go
- internal/dkg/execution.go
- internal/dkg/state_machine.go
We need to ensure the messages we are signing during the DKG process are encoded in the same way on both the signer and verifiers no matter what version or build of drand they are using.
This is building an explicit message instead of using the `String()` methods from protobuf which are not stable nor consistent across builds.
> Enforce a deterministic msg in dkg packet verification

- demo/node/node_subprocess.go
This should fix the issues we've had with our regression tests since the V2 merge into master.
> Prevent our regression tests using the empty string as a DB type

- Makefile
- common/version.go
- common/version_test.go
This ensures that a drand daemon built with the `insecure` tag will say so in its version output.
> Display `insecure` in the version when building without TLS

- internal/core/drand_beacon_public.go
- internal/drand-cli/cli_test.go
- internal/fs/fs_test.go
Since the relays are now talking gRPC it can happen the beacon hasn't yet been aggregated when a requests arrives. 
This is the equivalent of https://github.com/drand/drand/blob/ba859437579cd65e7f445a339ec140bcadd9264c/handler/http/server.go#L327-L366 but using our callback mechanism instead of channels and mutexes.
I'm not 100% convinced by my solution and I could probably achieve a better design on the relay side of things by relying on a PublicRandStream and doing the waiting on the relay side of things. 
WDYT?
> Honor gRPC requests for next beacon

- crypto/schemes.go
Despite it not being used in practice in drand
> This is explicitely setting the DST for G2 in the BN254 scheme

- common/time.go
- common/version.go
- docker/docker-compose.yml
- internal/core/drand_beacon_public.go
- internal/core/drand_test.go
~~This is a more stupid way of doing it. I didn't want to do that initially because I'm worried about the aggregation latency of \~400-700ms conflicting with the sleep, so using a callback which is guaranteed to be called when the next round is produced seemed much cleaner.~~
~~I'm tempted to do a +1 on the targetTime to mitigate for that.~~
Okay, ignore my first commit, I reverted to a callback to avoid the above problem, but now it's got a mutex and the impossible $2^{-128}$ edge case is removed.
Also changed the way the context and cancellations are handled.
All edgecases should also be covered now.
> Fixing panic in callback called twice for next beacon

- internal/core/drand_daemon_control.go
When we are creating a new keypair, but the DKG hasn't run yet, the beaconProcess for that beaconID exists already, but the chainhash doesn't exist yet.
We only report running chains through the ListBeaconIDs gRPC call now. Also don't hold the write mutex, just the read one in there.
> Only report chains that are past DKG

- internal/dkg/state_machine_test.go
- test/mock/grpcserver.go
Following this issue: https://github.com/drand/drand/issues/1137
Would like some advice is possible:
- `/test/mock/grpcserver.go`: I still have some places where panic is used. I have the feeling that a more complex refacto will be needed if we want to handle it. But not sure it is what we want ? Would like confirmation on this part.
- `/internal/test/test.go`: would like some advice on this one, should we want also to refacto the `FreeBind`. By instead of returning the string, returning an additional parameter that will be the error. But again, maybe too much refacto for it, and maybe not the scope of what we want. Again confirmation appreciated.
Feel free to tell me if you think some adjustment need to be done.
> test: use require instead of panic in tests

- common/version.go
- internal/chain/beacon/chainstore.go
- internal/chain/beacon/node.go
- internal/chain/beacon/store.go
- internal/chain/beacon/sync_manager.go
- internal/chain/beacon/ticker.go
I've discovered the culprit for our relatively large timing discrepancy in beacon production!
We were starting our ticker after waiting a given number of seconds without distinguishing whether the current second was already ticking or not. This PR adds extra tracing information and fixes the issue by relying on `clock.Until`, which is precise down to the nanosecond unlike how previous "second" resolution.
This PR brings a 97% decrease in beacon aggregation latency when doing local tests.
> Fixing our large timing discrepancy issue

- .github/workflows/publish_tagged.yaml
- common/log/log.go
- common/version.go
- demo/main.go
- internal/chain/beacon/node.go
- internal/chain/beacon/store.go
- internal/chain/beacon/sync_manager.go
- internal/metrics/metrics.go
- internal/metrics/threshold_monitor_test.go
- internal/net/control.go
Fixing edge case in sync and slight refactor.
The gist of the problem was that the `errChan` was un-buffered and thus blocking, waiting for a read during the send in the callback go routine.
> Fixing edge case in sync and slight refactor
