drand/drand

main.go, network.go, network_test.go, store.go
=> Connect tries multiple times

beacon/beacon_test.go, key/store.go, main.go
This has been found by https://github.com/mahrud , I'm just doing it now so it allows to have a testbed running locally in the same machine. See https://github.com/mahrud/drand/commit/b3e2e14ff3a088477b4b134aba1a5ae0486eac88 for original commit.
=> fix db folder path

main.go
=> TLS forbidden if running on windows

fs/fs.go, fs/fs_test.go, key/store.go, main_test.go, run_local.sh
=> Added permission checks

run_local.sh
=> Fix runlocal.sh on OSX

core/drand_control.go
=> fixing fatal in core/

control.go, run_local.sh
=> using absolute path for group file

net/listener_grpc.go
Follow the CloudFlare advice for limiting TLS backwards
compatibility.
Fixes #157.
=> Tighten up TLS config

control.go, main.go
=> Make the output of get public only valid JSON.

README.md
previous video was removed. replaced with accurate URL.
=> Update drand YouTube link

fs/fs.go
Makes it easier to understand what is wrong.
=> Print folder permissions warning in octal

.circleci/config.yml
* move the publish / deploy to dockerhub step into a CI step that only runs on merges to master
=> separate publishing from testing

beacon/handler.go, demo/main.go
=> Stabilizes test-integration on circleCI

Makefile, beacon/store.go, core/config.go, core/drand_test.go, go.mod, go.sum
=> CI should test with go's race detector

.github/labels.yml, .github/workflows/label-syncer.yml
=> feat: label taxonomy

core/client_test.go, core/config.go, core/drand_public.go, main.go, main_test.go
=> Explicit opt-in for private randomness feature

client/http_test.go, cmd/relay/main.go, go.mod, http/server.go, http/server_test.go
didn't notice the existing kit-log standard previously. lets make #290 a bit less of an issue
=> switch relay from ipfs-log to kit log

key/node.go
=> removing hashing address in group hash

demo/node.go
=> Fix port selection in node.

docs/DEPLOYMENT.md
think this is sufficient? additional explanation worth adding?
=> clarify public/private port

beacon/handler_test.go, client/http.go, key/group.go, key/group_test.go, main_test.go, test/mock/grpcserver.go, test/test.go
The issue was that the mock server is not returning the same genesis time in the group so the hash can be different.
=> Fix client http tests

README.md
=> docs: update license text in README

.circleci/config.yml, beacon/handler_test.go, core/drand_test.go
hopefully makes us dive a bit less deep into the logs
=> store test results for easier ci viewing

hooks/README.md, hooks/build
I tested on docker hub and it works
=> Set version and commit when building on Dockerhub

client/http_test.go, http/server.go, http/server_test.go, test/api/serve.go, test/mock/grpcserver.go
=> future-proof HTTP

.circleci/config.yml, Makefile, demo/demo_test.go, demo/main.go, demo/node/node.go, demo/node/node_inprocess.go, demo/node/node_subprocess.go, demo/orchestrator.go, net/control.go, test/test.go
=> Drand test driving

http/server.go
=> force json content type

cmd/relay-gossip/client/relayclient_test.go
Previously the code was creating files in the OS temp dir and subsequent test runs were using the same files. This PR fixes this by using the ioutil to create temporary directories within the OS temporary directory so that multiple test runs do not re-use the same files.
=> fix: use temporary dirs

chain/beacon_test.go
On my normal laptop (T480s)
```
BenchmarkVerifyBeacon-8              175           6245877 ns/op
```
=> adding benchmark for BLS

http/server.go
=> don't request next round requests that will fail

client/cache.go, client/cache_test.go, client/client.go, client/client_test.go, client/prioritizing.go, client/prioritizing_test.go, client/watcher.go, client/watcher_test.go, cmd/demo-client/main.go, cmd/relay-gossip/client/client.go, cmd/relay-gossip/client/relayclient_test.go, cmd/relay-gossip/main.go, test/mock/grpcserver.go
=> add validation routine for gossiped randomness

cmd/relay-gossip/client/client.go
The primary change is ignoring duplicates so they are not propagated
through the network.
=> Use extedned validator for pubsub

cmd/drand-cli/cli.go
=> fix error on help message

chain/beacon/chain.go, chain/beacon/constants.go
This reverts commit 41df34394f60b2cc867dc0bf9076deada9a1d890.
=> Revert "Fix chain cache DOS vuln (#533)" (#541)

cmd/client/lib/cli.go
=> revert grpc client to unwrapped

.github/workflows/toc.yml, README.md, docs/DEPLOYMENT.md, docs/METRICS.md, docs/SECURITY_MODEL.md, docs/SPECS.md
=> validate table of contents

docker/README.md, docker/docker-compose.yml
=> Bring Docker Compose script up to date

.golangci.yml, chain/beacon/cache_test.go, chain/boltdb/store.go, chain/info.go, client/aggregator.go, client/cache.go, client/client.go, client/grpc/client.go, client/http/http.go, client/optimizing.go, client/optimizing_test.go, cmd/client/lib/cli.go, cmd/client/main.go, cmd/relay-gossip/main.go, cmd/relay/main.go, core/config.go, demo/node/node_inprocess.go, http/server.go, log/log.go, log/log_test.go, lp2p/client/client.go, lp2p/client/relayclient_test.go, lp2p/ctor_test.go, lp2p/relaynode_test.go, metrics/metrics.go, net/certs.go, net/client_grpc.go, net/control.go, net/listener_with_tls.go, net/listener_without_tls.go
access to `DefaultLogger` changes to a method to avoid work in `init`
=> linting log package

lp2p/client/relayclient_test.go
I *think* the relay is publishing randomness _before_ the client has connected to it.
fixes #483
=> fix: flakey relay client test

go.mod, lp2p/addrutil.go, lp2p/addrutil_test.go, lp2p/ctor.go
Just some tests to increase coverage in the lp2p package.
=> test: add addrutil tests

.golangci.yml, cmd/client/lib/cli.go, cmd/client/lib/cli_test.go, cmd/client/main.go, cmd/drand-cli/cli.go, cmd/drand-cli/cli_test.go, cmd/drand-cli/control.go, cmd/drand-cli/daemon.go, cmd/drand-cli/public.go, cmd/relay-gossip/main.go, cmd/relay-s3/main.go, cmd/relay/main.go, metrics/metrics.go
a few functions with high complexity that should probably be broken up, but mostly through this one
=> linting of cmd/

go.mod, go.sum, lp2p/ctor.go
=> add noise transport

.github/workflows/lint.yml, .github/workflows/regression.yml, .github/workflows/release.yml, .goreleaser.yml, README.md, RELEASE.md, core/drand_control.go, core/drand_public.go, core/group_setup.go, demo/regression/main.go, go.mod, go.sum
* error messages are clearer in some reshare-failure scenarios
=> release v1.0.0

core/drand_control.go
=> clearer error msg

client/test/cache/cache.go, lp2p/client/client.go, lp2p/client/client_test.go, lp2p/client/validator.go, lp2p/client/validator_test.go
Adds tests for the pubsub randomness validator.
=> test: randomness validator

net/control.go
=> fix logic bug in changing catchup period in reshares

Makefile
```
➜  drand git:(master) ✗ make relay-http      
go build -o drand-relay-http -mod=readonly -ldflags "-X main.version=`git describe --tags` -X main.buildDate=`date -u +%d/%m/%Y@%H:%M:%S` -X main.gitCommit=`git rev-parse HEAD`" ./cmd/relay
➜  drand git:(master) ✗ ./drand-relay-http -v
drand HTTP relay v1.1.0-1-gb344575 (date 23/07/2020@15:09:08, commit b34457556cf9d7ecb20ba1da7f9ec83e7cbc75e1)
```
=> makefile rulse should properly inject tags

client/client.go, client/optimizing.go
=> protect gossip client from optimizer

chain/beacon/node_test.go, cmd/client/lib/cli.go, cmd/client/main.go, core/config.go, log/log.go
=> client verbose flag and logging to stderr

chain/beacon/store.go, chain/time.go, chain/time_test.go, core/drand_control.go, core/drand_test.go, metrics/metrics.go
=> add metric for latest stored round

chain/boltdb/store.go
Potential fix for https://github.com/drand/drand/issues/765
=> removing calling stats during init

.github/workflows/generate.yml, .github/workflows/lint.yml, cmd/drand-cli/cli.go, cmd/relay-gossip/main.go
hopefully fix some CI warning due to outdated action versions
=> update workflow action versions

http/server.go
=> Add caching headers on 404 responses

http/server.go
=> Attempt to time-out potentially stalled watches

.github/workflows/test.yml
lets see if this is all that's needed
=> add github test runner to release branch

go.mod, go.sum
Check also that you're happy with the commit I'm starting with as the start of the v1.3 release branch
=> bump kyber for stable sort

http/server.go, http/server_test.go
=> /public/0 should alias /public/latest in headers

Makefile, cmd/drand-cli/cli.go, cmd/drand-cli/control.go, cmd/drand-cli/daemon.go, cmd/drand-cli/public.go, cmd/relay/main.go, core/client_public.go, core/client_test.go, core/drand_daemon.go, core/drand_daemon_control.go, core/drand_test.go, core/util_test.go, demo/node/node_inprocess.go, http/server.go, net/control.go
it allows user to control different beacon processes running on daemon
=> Add beacon id to some cli commands

core/drand_control.go, go.mod, go.sum
=> adding logging 1.1.9 kyber

chain/beacon/store.go, metrics/metrics.go
@AnomalRoil @willscott Please check that all of the given metrics are actually per-beacon, and that I didn't miss any!
=> Add the beacon ID to some metrics

.github/workflows/release.yml, common/version.go
This should allow us to issue a testnet release successfully.
=> Preparing testnet release.

.github/workflows/release.yml
Might be useful to use `go install`...
=> Patching go releaser

.github/workflows/release.yml
Hopefully that's the last one...
=> wrong path in go releaser

chain/beacon/sync_manager.go, core/drand_beacon_public.go
Another potential nil deref panic.
=> Do not call metadata if Nil

cmd/relay/main.go
See if you're happy with this setup for separating the child contexts
=> relay makes sub-contexts for different clients

chain/beacon/node_test.go, chain/beacon/store_test.go, chain/convert.go, chain/info.go, chain/info_test.go, chain/store.go, client/test/result/mock/result.go, client/verify.go, cmd/client/lib/cli.go, cmd/drand-cli/public.go, cmd/relay/main.go, core/drand_beacon.go, core/drand_beacon_control.go, core/drand_daemon.go, core/drand_daemon_helper.go, core/drand_test.go, core/util_test.go, net/control.go
To fix our current issue on the relays.
=> Ignore empty flags and better chain hash handling.

.github/workflows/publish_tagged.yaml
=> Use new drandci account for CI

metrics/metrics.go
=> make sure metrics are bound for use with grouphandler

cmd/drand-cli/public.go, core/drand_beacon_control.go
* deduped some vars in group extraction
=> Corrected an incorrectly updated CLI flag

core/drand_beacon_control.go
=> Fixed bug where prior threshold would be 0 for DKGs

core/drand_beacon.go, core/drand_test.go, core/util_test.go, key/store.go
For example, changing the TLS settings
=> Fixed segfault when a user manually updates their group file

core/drand_beacon_metrics.go, metrics/metrics.go, metrics/metrics_test.go
=> Fixed segfault in serving metrics

core/drand_beacon.go
=> Adding a debug log

cmd/drand-cli/cli.go
=> Fix confusing group file message

chain/beacon/chain.go, chain/beacon/sync_manager.go, core/broadcast.go, core/broadcast_test.go, core/drand_beacon_control.go, core/drand_beacon_public.go, core/group_setup.go, core/util_test.go
Converting wrong `Debug` logs into `Error` and upping some logs to `Info` level.
=> Reworking some logs

core/util_test.go
=> Fixing linter for RunDKG

chain/beacon/store.go
When computing the `time_discrepancy`, time.Now() should be obtained as close as possible to receiving the beacon, before any other storage layer interaction.
When moved after store.Put(), the value will include the time it takes the storage layer to store the value, making it inaccurate.
The time it takes to store a new beacon will now be recorded as a separate value in the logs.
Sample log output, observe the new `storage_time_ms` value in logs:
```
2022-11-18T15:28:54.574+0200    INFO    127.0.0.1:61105.default.3       beacon/chain.go:176             {"aggregated_beacon": 27589}
2022-11-18T15:28:54.587+0200    INFO    127.0.0.1:61105.default.3       beacon/store.go:137             {"NEW_BEACON_STORED": "{ round: 27589, sig: 8c45cb, prevSig: a30853 }", "time_discrepancy_ms": 574.09385, …
```
=> Compute the time discrepancy of beacons without the storage layer latency

demo/demo_test.go
In the current implementation, the test will not timeout and cancel due to the way `t.Fatal` works in relation to `time.AfterFunc`.
This PR updates the test to make sure we cancel after 3 minutes.
=> Fix test timeout

cmd/drand-cli/cli.go
This PR adds the flags in https://github.com/drand/drand/pull/1099 as hidden flags.
=> Add hidden in-memory buffer size flag in preparation for #1099

key/group.go
Migration path from < v1.3 for loading scheme name in group
=> Migration path from < v1.3 for loading scheme name in group

common/version.go
In order to test our new release.
=> Tagging v1.5.0-testnet

cmd/client/lib/cli.go, common/version.go, core/drand_daemon_interceptors.go, demo/demo_test.go
=> Quick fix to support v1.4 from v1.5 nodes

common/version.go
Bumping minor to v1.5.3-testnet
=> Bumping minor to v1.5.3-testnet

cmd/drand-cli/cli_test.go, core/drand_beacon.go
Add extra logging and a test for this.
=> Instead of fetching the current-1, load the latest stored beacon from the network

cmd/drand-cli/cli.go, common/version.go, core/drand_beacon_public.go
In order to finally tag v1.5.3
=> Removing testnet pre-release tag and fixing util check

.github/workflows/publish.yaml, .github/workflows/publish_tagged.yaml
Will create a separate PR once this one is merged to move all the images used in the repo to point to the gchr one
=> moved from dockerhub to github container registry

common/version.go
Let's not forget to bump the version this time.
=> Getting ready for tagging v1.5.4

cmd/drand-cli/cli_test.go, cmd/drand-cli/dkg_cli.go, core/drand_beacon.go, dkg/actions_active.go, dkg/state_machine.go, go.mod, go.sum
- fixed a bug where the transition time was 0 for initial DKG
- increased genesis time for tests due to the memdb test getting some
weird sync deadlock
=> improved output for DKG status command

.github/CODEOWNERS
Applying #1222 against develop too.
=> Avoid notifying everyone for develop PRs

http/server.go, http/server_test.go
=> return 404 when no beacon hash exists instead of 500

.github/workflows/docker-build.yml, Dockerfile, cmd/client/Dockerfile
- added a github action step for building the docker image on branches to ensure compat
=> updated dockerfiles to use go 1.20

.github/workflows/release.yml, .goreleaser.yml
=> Update release.yml to 4.3.0

demo/node/node_subprocess.go, internal/chain/beacon/node.go, internal/core/drand_beacon.go, internal/core/drand_beacon_test.go, internal/core/drand_test.go, internal/core/util_test.go, internal/drand-cli/cli_test.go, internal/test/docker/docker-compose.yml, internal/test/local.sh
We are not supposed to have more than one handlers loop running at once.
=> Don't use more than 1 handler

common/version.go
=> Updating version to v1.5.7 for mainnet release

chain/beacon/node.go, client/doc.go, client/interface.go, core/constants.go, core/drand_beacon.go, core/drand_beacon_control.go, core/drand_daemon_control.go, core/drand_proxy.go, core/group_setup.go, core/util_test.go, docker/start-network.sh, lp2p/client/client.go, test/mock/grpcserver.go
Text corrections on multiple go files
=> Text corrections on multiple go files

common/client/interface.go, docker/start-network.sh, internal/core/constants.go, internal/test/mock/grpcserver.go
=> Cherry picking typos corrections

internal/drand-cli/control.go
Currently we don't process all beacons properly when self-signing upon boot. This fixes it.
=> Properly process all beacons when self-signing

common/version.go, common/version_test.go
To keep both compatible hopefully!
=> Merging version changes from master to v2

common/beacon.go, common/chain/convert.go, common/key/group.go, common/key/keys.go, crypto/schemes.go, crypto/schemes_test.go, demo/node/node_inprocess.go, demo/node/node_subprocess.go, docker/start-network-with-nginx.sh, docker/start-network.sh, internal/dkg/actions_active.go, internal/dkg/execution.go, internal/dkg/state_machine.go
What it says: Applying some of the code review comments from #1283 to it
=> Applying some of the code review comments to v2

common/version.go
This is the very last release before v2, hopefully.
=> v1.5.9 release

Makefile, common/key/keys.go, common/version.go, crypto/schemes.go
=> Fixing make install

common/key/store.go, internal/core/drand_beacon.go, internal/core/drand_daemon_helper.go, internal/test/key_store.go
Removing unused ResetOptions
Plus a few misc changes to comments and using properly nil-guarded functions for getting protobuf fields.
=> Removing unused ResetOptions

internal/core/drand_test.go, internal/core/util_test.go, internal/dkg/actions_active_test.go, internal/dkg/state_machine.go, internal/dkg/state_machine_test.go, internal/dkg/store.go, internal/dkg/store_test.go, internal/drand-cli/dkg_cli.go, internal/drand-cli/dkg_repair.go
DKG nuke command to easily delete a single beacon's state, should you need to
=> DKG nuke command

internal/net/client_grpc.go
=> Removing TLS fallback

.github/workflows/lint.yml, .github/workflows/regression.yml, internal/dkg/actions_active.go, internal/net/conn_other.go
=> Fixing our tests hopefully

common/key/group_test.go, internal/chain/beacon/node.go, internal/metrics/threshold_monitor.go, internal/metrics/threshold_monitor_test.go
- added a test to group.len() to ensure it returns the right thing
=> corrected threshold monitor reporting

common/version.go, net/client_grpc.go
Which was done in #1315 for v2
=> Backporting grpc Close fix

common/key/store.go, internal/core/drand_beacon.go, internal/core/drand_daemon.go, internal/core/drand_daemon_control.go, internal/dkg/actions_active.go, internal/drand-cli/control.go, test/regression/regression_test.go, test/regression/secretfile
- added some regression tests against v1.5.7
=> fixed bug where offline leavers would block proposals

internal/dkg/actions_active.go, internal/dkg/actions_active_test.go, internal/dkg/actions_passive.go, internal/dkg/dkg_process_test.go, internal/dkg/state_machine.go
Previously it would work if the participants across epochs were the same, so it went unnoticed.
=> fixed a bug where DKG could not be recovered from an abort

FUNDING.json
=> Connecting to Drips network

internal/chain/boltdb/store.go, internal/chain/store.go, internal/core/drand_beacon.go, internal/core/drand_daemon.go, internal/metrics/metrics.go
Also changing the place where we set the metrics for the DB
=> Adding a metric for trimmed-bolt vs untrimmed-bolt

.github/workflows/lint.yml, .golangci.yml, Makefile, common/beacon.go, internal/chain/beacon/node.go, internal/chain/memdb/store.go, internal/chain/postgresdb/database/database.go, internal/chain/postgresdb/pgdb/pgdb.go, internal/chain/store.go, internal/core/config.go, internal/core/constants.go, internal/core/drand_beacon.go, internal/core/drand_daemon_control.go, internal/core/drand_test.go, internal/core/util_test.go, internal/dkg/broadcast.go, internal/drand-cli/cli.go, internal/net/control.go, internal/net/gateway.go, internal/net/listener.go
Renaming gomnd -> mnd, and updating our GHA.
=> Updating our linter to 1.58

internal/core/util_test.go, internal/dkg/actions_passive.go, internal/dkg/actions_signing.go, internal/dkg/dkg_runner.go, internal/drand-cli/dkg_cli.go, internal/drand-cli/dkg_cli_test.go
Just to make it prettier and clearer who has accepted and who hasn't accepted yet.
=> Adding checkmarks to DKG status output

.pre-commit-config.yaml, docker/cleanup.sh, internal/metrics/metrics.go, internal/net/control_test.go
Since @GlacierWalrus requested these...
=> Adding precommit hooks

LICENSE-APACHE
So that Github recognizes it correctly.
=> Using full text apache 2 license

.github/workflows/generate.yml, .github/workflows/lint.yml, .github/workflows/publish_tagged.yaml, .github/workflows/regression.yml, .github/workflows/release.yml, .github/workflows/tests.yaml, common/version.go, demo/lib/orchestrator.go, demo/node/node_subprocess.go, demo/regression/main.go
=> Preparing release v2.1.0

.github/workflows/lint.yml, .golangci.yml, .pre-commit-config.yaml, common/beacon.go, common/beacon_test.go, common/chain/convert.go, common/chain/info.go, common/chain/info_test.go, internal/chain/beacon/sync_manager.go, internal/dkg/actions_active.go, internal/drand-cli/cli_test.go, internal/drand-cli/control.go
Fixes #444 for real. 
(I needed it for some other project anyway.)
Also fixing some new linter issues.
=> Actually implementing Json marshmaller for chain.Info

README.md
Removing dead links from readme
=> Removing dead links from readme
